### PR TITLE
Fix auto-posting tweets for automatically published posts.

### LINKED ISSUE #286: auto sharing not working
### Describe your question

every post, need to go edit, and tweet manually from the post editor. help pls. settings are all fine. double, tripple checked!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #287: WP Automatic posts not autoshared
### Describe your question

Hi,

I'm using "WordPress Automatic" to automatically create posts, but in this case, they are not shared on Twitter. Is there a way to make it work?

Regards,
Mikael

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by iamdharmesh**
### Description of the Change
The PR addresses issues with auto-posting tweets for automatically published posts. Currently, tweets are posted based only on tweet accounts saved in post meta, and these tweet accounts are saved to post meta in the edit post screen. Because of this, when posts are automatically published, they don't get tweeted. The PR resolves this issue by tweeting posts to accounts with auto-share enabled by default when post meta is not saved in the post.

Closes #287 
Closes #286 

### How to test the Change
1. Install and set up the plugin.
1. Connect Twitter account.
1. Enabled Autoshare by default on the connected account.
1. Automatically publish post, It can be done via the below code snippet or you can follow any other way to do this.
```php
add_action( 'init', function(){
	// Create a new post.
	wp_insert_post(
		array(
			'post_title'  => 'Test Title',
			'post_status' => 'publish',
		)
	);
});
```
1. Verify that the post has been tweeted.

### Credits

Props @iamdharmesh @sunnmagic

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

**Comment by sunnmagic** [comment]
Hi,

Great, how can we install the new version?

**Comment by peterwilsoncc** [comment]
@iamdharmesh I tested this but it doesn't appear to be working for me, see the gif below.

auto-share-generated

Along with WP CLI, I also tried the code above using the `init` hook but without success.

**Comment by jeffpaul** [comment]
@sunnmagic this fix is not yet ready or part of a released version but for now we're targeting this in the 2.2.0 release.

**Comment by sunnmagic** [comment]
Ok I see, do you know when it will be released?

**Review by peterwilsoncc — APPROVED** [review]
This LGTM.

I re-tested and discovered I was hitting a false negative in `AST_Staging::is_production_site()` when testing via WP-CLI earlier.

The code wasn't working for me on `init` as I was registering it as an mu-plugin on `init, 10` so it running prior to the plugin registering post support (as discussed offline yesterday).

@iamdharmesh, you mentioned changing the post type support function to run earlier on `init` but I don't think that will work as the common code example for registering post type is:

```php
add_action( 'init', /* register_post_type() */ );
```

So registering post type support prior to `init, 10` will miss any CPTs that are registered by plugins. If anything we should probably register it later on the init hook.

It might be worth testing that in a follow up issue though. I think this can be merged as is.

**Pull request merged**
