### PR TITLE
fix: use save_post to publish tweet for classic editor

### LINKED ISSUE #112: Post Transition and Twitterbot Scraping Timing
Hi team,

We have run into issues on a client project where the Twitter card/Twitterbot does not fetch the featured image. VIPs diagnosis is that our transition_post_status hook is firing too early before all the appropriate Yoast meta can be set. 

Here is the report from VIP team:

"I looked at the php error logs and origin & load balancer request logs for timeframes around some of the items that were published.

This for example is the logging that was already in place for this story: https://twitter.com/9to5toys/status/1337072730714337280

    Dec 10, 2020 @ 16:32:29.000 [10-Dec-2020 16:32:29 UTC] VIPDEBUG: post transition from draft to publish POST: 649991 post_date: 2020-12-10 11:32:29  Container #106864   
    Dec 10, 2020 @ 16:32:35.000 [10-Dec-2020 16:32:35 UTC] VIPDEBUG: post transition from publish to publish POST: 649991 post_date: 2020-12-10 11:32:29    Container #111775   
    Dec 10, 2020 @ 16:32:43.000 [10-Dec-2020 16:32:43 UTC] VIPDEBUG: post transition from publish to publish POST: 649991 post_date: 2020-12-10 11:32:29    Container #68362    
    Dec 10, 2020 @ 16:32:49.000 [10-Dec-2020 16:32:49 UTC] VIPDEBUG: post transition from publish to publish POST: 649991 post_date: 2020-12-10 11:32:29    Container #81683    
The subsequent-to-publish changes (which happen on different origin web containers) seem to occur from these POST requests: /wp-json/wp/v2/posts/649991?_locale=user

It's unclear what those changes are. Even outside of the AJAX/REST requests, we know that many things do hook on the same post transition and can make additional changes to the post content or its metadata.

LB logs show Twitterbot requested the URL at Dec 10, 2020 @ 16:32:35.000 which is in the middle of those changes. And then the next Twitterbot request was at Dec 10, 2020 @ 16:34:10.000 (2 requests) and then the next an hour later.

I think one possibly way to try to deal with possible race conditions (where a post transitioned to published but all the metadata hadn't updated yet and Twitter is fetching possibly older data, or is requesting an image URL that for some reason later changes) would be to either give the tweet action hook a much later priority, or move the actual tweet action to a cron event that is scheduled "immediately" when the post transitions to published."

### PR DESCRIPTION
**Pull request by dinhtungdu**
Fixes #112

### CODE REVIEW

**Comment by jeffpaul** [comment]
@rickalee @dkotter either of you able to help review this?

**Comment by dinhtungdu** [comment]
Note that the unit test is failing and it's expected because the internal function change. The unit test case needs to be updated accordingly.

**Review by dkotter — DISMISSED** [review]

**Comment by dkotter** [comment]
Code looks good to me but I don't have a setup to test this, so would be ideal if someone that can reproduce the original issue can test if this fixes it. Also, @dinhtungdu noticing there are changes to the `composer.lock` file. Are those necessary as part of this PR?

**Comment by dinhtungdu** [comment]
> Also, @dinhtungdu noticing there are changes to the `composer.lock` file. Are those necessary as part of this PR?

It's an attempt to fix the failing test on PHP 7.1 and 7.2. It says our lock file is out of date.

**Comment by dinhtungdu** [comment]
@jeffpaul Merging this one should fix the failed actions in other PR

**Comment by rickalee** [comment]
@dinhtungdu How would this affect our hook priority in Block editor to fix #112? Site with issue in #112 is using Block editor vs Classic.

**Pull request closed without merging**
