### PR TITLE
Update plugin name and branding

### PR DESCRIPTION
**Pull request by jeffpaul**
### Description of the Change
This PR works to rename from "Autoshare for Twitter" to "Autopost for X (formerly Autoshare for Twitter)" (where we can drop the part in parens at a later date) as well as updates references of "Twitter" to "X/Twitter" (where we can drop the Twitter part at a later date).  Also pending will be an update of the banner/icon images.

There's still all the PHP/JS files to go through here on the renaming, hoping @iamdharmesh can help finish that off.

### Changelog Entry

> Changed - Renamed plugin from "Autoshare for Twitter" to "Autopost for X (formerly Autoshare for Twitter)".

### Credits

Props [Morgan Hartnett](https://www.morganhartnett.com/), @jeffpaul.

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

**Comment by jeffpaul** [comment]
@iamdharmesh I'm working to get the banner/icon updates ready, so if you can help update the remaining files here for the renaming that will help unblock this change for release before year end... thanks!

**Comment by iamdharmesh** [comment]
@jeffpaul I have updated Twitter references in Codebase. Now, the below things are pending to make this ready for merge, I will update it once I get the updated banner and icons.
1. **WP.org assets**
1. **Icons in list table and sidebar panel**
1. **Screenshots**


Also, Just wanted to double-confirm that, is it fine to keep using "Tweet" wording here Or we should update it with "Post"?
|||
|---|---|
|image|image|

Thanks

**Comment by jeffpaul** [comment]
> Also, Just wanted to double-confirm that, is it fine to keep using "Tweet" wording here Or we should update it with "Post"?

Ugh, yeah, I suppose best to update to Post though maybe let's do...
`Autopost to X/Twitter enabled`
`Post to X/Twitter when published`
`Use featured image in Post to X/Twitter`
`Autopost to X/Twitter`
`Posted to X/Twitter on...`
`Post to X/Twitter now`
`Post to X/Twitter again`

**Comment by jeffpaul** [comment]
@iamdharmesh FYI that the updated banner/icon images are included in this PR

**Comment by iamdharmesh** [comment]
@jeffpaul This is now ready for your review. Please let me know if you want to see this running, I will help with setting up the plugin from this branch on the instawp instance.

**Comment by jeffpaul** [comment]
@iamdharmesh yes, a test instance would be helpful to preview/test to ensure we've captured all the renaming locations

**Comment by jeffpaul** [comment]
Some items from testing:

1. Would be good to expand the column for the labels on the Settings page so they can appear on a single row (none are too long)

Screenshot 2023-12-14 at 11 59 08 AM

2. Update Autoshare to Autopost

Screenshot 2023-12-14 at 12 00 31 PM

3. Update auto-tweet to auto-post and Tweet to Post.

Screenshot 2023-12-14 at 12 01 21 PM

4. Update text in this scenario from "This post was not posted to X/Twitter." to "This post has not been posted to X/Twitter."

Screenshot 2023-12-14 at 12 04 38 PM

5. Update button text in this scenario to "Post to X/Twitter"

Screenshot 2023-12-14 at 12 05 52 PM

6. Update hover-text from `Tweeted status` to `Autopost status` (header row & footer row)

Screenshot 2023-12-14 at 12 07 54 PM

7. There's no hover text in the sample above where the page hasn't been posted to x, would probably be good to add something like "Has not been Posted to X/Twitter"

8. Screen Options display update from "Tweeted status" to "Posted to X/Twitter status"

Screenshot 2023-12-14 at 10 27 01 PM

9. Worth scanning remaining codebase in the branch for additional references of "tweet", "Twitter", and "autoshare" to see if there are other places we've missed that are user-facing

**Comment by iamdharmesh** [comment]
@jeffpaul Thanks for the feedback, I have addressed it and updated the latest branch to Instawp instance.

**Comment by jeffpaul** [comment]
Looks good @iamdharmesh, thanks!

**Review by iamdharmesh — APPROVED** [review]

**Pull request merged**
