### PR TITLE
Fix our pipeline failures

### PR DESCRIPTION
**Pull request by dkotter**
### Description of the Change

Pipelines are currently failing due to the use of composer v2. This PR pulls the pipeline fixes from #117 in order to try and fix this

### Alternate Designs

Could update our scripts to work with composer v2 instead of continuing to use v1

### Benefits

Pipelines won't needlessly fail

### Possible Drawbacks

None

### Verification Process

Ensure the pipeline for this PR passes

### CODE REVIEW

**Comment by dkotter** [comment]
All tests now pass besides the WP Acceptance test (which only runs in the PHP 7.2 container). Currently the WP Acceptance tests aren't running, as things fail when getting the snapshot set up:
```Creating environment...
Creating containers...
Running tests...
Setting up WordPress test environment from snapshot.
Failed to pull snapshot into WordPress container.
Could not setup WordPress environment.

**Comment by dinhtungdu** [comment]
I got the below error while I was testing this PR locally:
image

The wpacceptance docker image still uses the previous version of wpsnapshots (v 2.01). That's why the action hangs on pulling snapshot.

**Comment by jeffpaul** [comment]
@dkotter @dinhtungdu noting that we'll probably want to refresh this to remove WPA in favor of our newer e2e testing approach and unblock the AS4T release, but no rush on that as this is a lower priority release and best to get Simple Podcasting and RSA updated with e2e tests first.

**Comment by iamdharmesh** [comment]
Closing in favor of #147

**Pull request closed without merging**
